name: QA Deploy

on:
  push:
    branches:
      - 'rc'
  workflow_dispatch:
    inputs: 
      migrateDb:
        required: true
        default: "true"
      resetDb:
        required: true
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Api
            base_path: .
          - name: Admin
            base_path: .
            gulp: true
          - name: Billing
            base_path: .
          - name: Events
            base_path: .
          - name: Notifications
            base_path: .
          - name: Sso
            base_path: ./bitwarden_license
            gulp: true
          - name: Portal
            base_path: ./bitwarden_license
            gulp: true
          - name: Identity
            base_path: .
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Print Environment
        run: |
          dotnet --info
          node --version
          npm --version
          gulp --version

      - name: load env vars
        run: |
          echo "Base Path: ${BASE_PATH}"
          echo "Name: ${NAME}"
        env:
          BASE_PATH: ${{ matrix.base_path }}
          NAME: ${{ matrix.name }}

      - name: Build Service
        run: |
          work_dir=$(pwd)
          dir=$BASE_PATH/src/$SERVICE_NAME

          cd $dir
          echo "Restore"
          dotnet restore $SERVICE_NAME.csproj
          echo "Clean"
          dotnet clean $SERVICE_NAME.csproj -c "Release" -o obj/Azure/publish

          if [ "$GULP" == "true" ]; then
            npm install
            npm install gulp
            gulp --gulpfile gulpfile.js build
          fi

          echo "Publish"
          dotnet publish $SERVICE_NAME.csproj -c "Release" -o obj/Azure/publish

          cd obj/Azure/publish
          zip -r $SERVICE_NAME.zip .
          mv $SERVICE_NAME.zip ../../../
        env:
          SERVICE_NAME: ${{ matrix.name }}
          BASE_PATH: ${{ matrix.base_path }}
          GULP: ${{ matrix.gulp }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.SERVICE_NAME }}.zip
          path: ${{ env.BASE_PATH }}/src/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}.zip
        env:
          BASE_PATH: ${{ matrix.base_path }}
          SERVICE_NAME: ${{ matrix.name }}

      - name: Test build dir
        run: ls $BASE_PATH/src/$SERVICE_NAME
        env:
          SERVICE_NAME: ${{ matrix.name }}
          BASE_PATH: ${{ matrix.base_path }}


  reset-db:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Reset Test Data - Stub
        if: ${{ github.events.inputs.resetDb }} == "true"
        run: |
          echo "placeholder for cleaning DB"
          echo "placeholder for loading test dataset"

  update-db:
    if: ${{ github.events.inputs.migrateDb }} == "true"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: migrate db
        if: ${{ github.events.inputs.resetDb }} == "true"
        run: |
          echo "placeholder for updateing DB"


  deploy-identity:
    runs-on: ubuntu-latest
    needs: 
      - reset-db
      - update-db
    steps:
      - name: Download aritifacts
        uses: actions/download-artifact@v2
        with:
          name: Identity.zip

      - name: Login to Azure
        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
        with:
          creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: Azure/get-keyvault-secrets@80ccd3fafe5662407cc2e55f202ee34bfff8c403
        with:
          keyvault: "bitwarden-qa-kv"
          secrets: "appservices-identity-webapp-name"

      - name: Get Publish Profile
        id: get-pp
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-identity-webapp-name }} 
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Deploy Identity
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.retrieve-secrets.outputs.appservices-identity-webapp-name }} 
          slot-name: "staging"
          publish-profile: ${{ steps.get-pp.outputs.profile}} 
          package: ./Identity.zip

      - name: Reset Publish Profile
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-identity-webapp-name }} 
          reset: true
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}


  deploy-api:
    runs-on: ubuntu-latest
    needs: 
      - reset-db
      - update-db
    steps:
      - name: Download aritifacts
        uses: actions/download-artifact@v2
        with:
          name: Api.zip

      - name: Login to Azure
        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
        with:
          creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: Azure/get-keyvault-secrets@80ccd3fafe5662407cc2e55f202ee34bfff8c403
        with:
          keyvault: "bitwarden-qa-kv"
          secrets: "appservices-api-webapp-name"

      - name: Get Publish Profile
        id: get-pp
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-api-webapp-name }} 
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Deploy Api
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.retrieve-secrets.outputs.appservices-api-webapp-name }} 
          slot-name: "staging"
          publish-profile: ${{ steps.retrieve-secrets.outputs.appservices-api-webapp-publish-profile }} 
          package: ./Api.zip

      - name: Reset Publish Profile
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-api-webapp-name }} 
          reset: true
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}


  deploy-billing:
    runs-on: ubuntu-latest
    needs: 
      - reset-db
      - update-db
    steps:
      - name: Download aritifacts
        uses: actions/download-artifact@v2
        with:
          name: Billing.zip

      - name: Login to Azure
        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
        with:
          creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: Azure/get-keyvault-secrets@80ccd3fafe5662407cc2e55f202ee34bfff8c403
        with:
          keyvault: "bitwarden-qa-kv"
          secrets: "appservices-billing-webapp-name"

      - name: Get Publish Profile
        id: get-pp
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-billing-webapp-name }} 
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Deploy Billing
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.retrieve-secrets.outputs.appservices-billing-webapp-name }} 
          slot-name: "staging"
          publish-profile: ${{ steps.retrieve-secrets.outputs.appservices-billing-webapp-publish-profile }} 
          package: ./Billing.zip

      - name: Reset Publish Profile
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-billing-webapp-name }} 
          reset: true
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}


  deploy-events:
    runs-on: ubuntu-latest
    needs: 
      - reset-db
      - update-db
    steps:
      - name: Download aritifacts
        uses: actions/download-artifact@v2
        with:
          name: Events.zip

      - name: Login to Azure
        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
        with:
          creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: Azure/get-keyvault-secrets@80ccd3fafe5662407cc2e55f202ee34bfff8c403
        with:
          keyvault: "bitwarden-qa-kv"
          secrets: "appservices-events-webapp-name"

      - name: Get Publish Profile
        id: get-pp
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-events-webapp-name }} 
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Deploy Events
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.retrieve-secrets.outputs.appservices-events-webapp-name }} 
          slot-name: "staging"
          publish-profile: ${{ steps.retrieve-secrets.outputs.appservices-events-webapp-publish-profile }} 
          package: ./Events.zip

      - name: Reset Publish Profile
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-events-webapp-name }} 
          reset: true
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}


  deploy-sso:
    runs-on: ubuntu-latest
    needs: 
      - reset-db
      - update-db
    steps:
      - name: Download aritifacts
        uses: actions/download-artifact@v2
        with:
          name: Sso.zip

      - name: Login to Azure
        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
        with:
          creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: Azure/get-keyvault-secrets@80ccd3fafe5662407cc2e55f202ee34bfff8c403
        with:
          keyvault: "bitwarden-qa-kv"
          secrets: "appservices-sso-webapp-name"

      - name: Get Publish Profile
        id: get-pp
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-sso-webapp-name }} 
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Deploy SSO
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.retrieve-secrets.outputs.appservices-sso-webapp-name }} 
          slot-name: "staging"
          publish-profile: ${{ steps.retrieve-secrets.outputs.appservices-sso-webapp-publish-profile }} 
          package: ./Sso.zip

      - name: Reset Publish Profile
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-sso-webapp-name }} 
          reset: true
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}


  deploy-portal:
    runs-on: ubuntu-latest
    needs: 
      - reset-db
      - update-db
    steps:
      - name: Download aritifacts
        uses: actions/download-artifact@v2
        with:
          name: Portal.zip

      - name: Login to Azure
        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
        with:
          creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: Azure/get-keyvault-secrets@80ccd3fafe5662407cc2e55f202ee34bfff8c403
        with:
          keyvault: "bitwarden-qa-kv"
          secrets: "appservices-portal-webapp-name"

      - name: Get Publish Profile
        id: get-pp
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-portal-webapp-name }} 
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Deploy Portal
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.retrieve-secrets.outputs.appservices-portal-webapp-name }} 
          slot-name: "staging"
          publish-profile: ${{ steps.retrieve-secrets.outputs.appservices-portal-webapp-publish-profile }} 
          package: ./Portal.zip

      - name: Reset Publish Profile
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-portal-webapp-name }} 
          reset: true
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}


  deploy-admin:
    runs-on: ubuntu-latest
    needs: 
      - reset-db
      - update-db
    steps:
      - name: Download aritifacts
        uses: actions/download-artifact@v2
        with:
          name: Admin.zip

      - name: Login to Azure
        uses: Azure/login@77f1b2e3fb80c0e8645114159d17008b8a2e475a
        with:
          creds: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Retrieve secrets
        id: retrieve-secrets
        uses: Azure/get-keyvault-secrets@80ccd3fafe5662407cc2e55f202ee34bfff8c403
        with:
          keyvault: "bitwarden-qa-kv"
          secrets: "appservices-admin-webapp-name"

      - name: Get Publish Profile
        id: get-pp
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-admin-webapp-name }} 
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

      - name: Deploy Admin
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ steps.retrieve-secrets.outputs.appservices-admin-webapp-name }} 
          slot-name: "staging"
          publish-profile: ${{ steps.retrieve-secrets.outputs.appservices-admin-webapp-publish-profile }} 
          package: ./Admin.zip

      - name: Reset Publish Profile
        uses: aliencube/publish-profile-actions@0689f99a0d742938bbe312db9e366e8716cb0855
        with:
          resrouceGroupName: "bitwarden-qa"
          appName: ${{ steps.retrieve-secrets.outputs.appservices-admin-webapp-name }} 
          reset: true
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_QA_KV_CREDENTIALS }}

